<?php
require_once dirname(__FILE__) . '/includes/queries.inc';
require_once dirname(__FILE__) . '/includes/reports.form.inc';

/**
 * Implements hook_menu().
 */
function islandora_content_stats_menu() {
  $items = array();
  $items['admin/islandora/tools/content_stats'] = array(
    'title' => 'Content Statistics Admin',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_content_stats_admin_form',1),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
  );
  $items['admin/reports/content_stats'] = array(
    'title' => 'Content Statistics Report Last Run',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_content_stats_table_form', 1),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/reports.form.inc',
  );
  $items['admin/reports/content_stats/all'] = array(
    'title' => 'Content Statistics Report All Queries',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_content_stats_table_all_form', 1),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/reports-all.form.inc',
  );
  return $items;
}


islandora_content_stats_post_collection_stats();
function islandora_content_stats_post_collection_stats(){
  if(strpos(current_path(),'collection')){
    $str =current_path();
    $coll = str_replace('islandora/object/','',$str);
    islandora_content_stats_page_cmodels($coll);
  }
}


function check_path(){
  $one_of_these = update_namespace_prefixes_cache();
      if(in_array(str_replace('/','',request_uri()), $one_of_these)){
        return true;
      }
}

islandora_content_stats_post_institution_stats();
function islandora_content_stats_post_institution_stats(){
  if(!preg_match("/([\/]\w+[\/]\w+)/", request_uri())){
    if(check_path()){
      islandora_content_stats_page_cmodels(str_replace('/','',request_uri()));
    }
  }
}

/**
* Implements hook_block_info().
*/
function islandora_content_stats_block_info() {
  $blocks = array();
    $blocks['content_stats'] = array(
      'info' => t('Content Stats'),
      'cache' => DRUPAL_CACHE_PER_USER
    );
  return $blocks;
}

function islandora_content_stats_block_view($delta = ''){
$blocks = array();
  switch ($delta) {
    case 'content_stats':
      $blocks['subject'] = t('Content Stats Block');
      $blocks['content'] = drupal_get_form('islandora_content_stats_table_form');
      break;
  }
  return $blocks;
}
