<?php

/**
 * Implements hook_menu().
 */
function islandora_content_stats_menu() {
    $items = array();
    $items['admin/islandora/tools/content_stats'] = array(
        'title' => 'Content Statistics',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('islandora_content_stats_admin_form', 1),
        'access arguments' => array('administer site configuration'),
        'file' => 'includes/admin.form.inc',
    );
        $items['data'] = array(
        'title' => 'Content Statistics',
        'page callback' => 'islandora_content_stats_data',
        'page arguments' => array('islandora_content_stats_form'),
        'file' => 'includes/data.form.inc',
        'access callback' => TRUE,
    );
    return $items;
}

function islandora_content_stats_data() {
    return theme('islandora_content_stats_data_tpl');

}

function islandora_content_stats_theme() {
    module_load_include('inc','islandora_content_stats','includes/language');
    module_load_include('inc','islandora_content_stats','includes/utilities');
    module_load_include('inc','islandora_content_stats','includes/queries');
    module_load_include('inc','islandora_content_stats','includes/data.form');
    $flform = drupal_get_form('islandora_content_stats_data_filter_form');
    return array(
        'islandora_content_stats_data_tpl' => array(
            'template' => 'theme/data',
            'render element' => 'form',
            'variables' => array(
                'global_totals' => global_totals(),
                'inst_totals' => inst_totals(),
                'lang_desc' => lang('data_description'),
                'lang_filter' => lang('filter_fieldset_#title'),
                'lang_table' => lang('table-collapse_fieldset_#title'),
                'lang_table_desc' => lang('table-collapse_explain'),
                'last_run' => gmdate("M d Y H:i:s", latest_run()),
                'filter_form' => $flform,
            ),
        ),
    );
}

function template_preprocess_islandora_content_stats_data_tpl(&$variables) {
  module_load_include('inc','islandora_content_stats','includes/utilities');
  module_load_include('inc','islandora_content_stats','includes/data.form');
  $variables['latest'] = latest_counts_for_table($_GET);
  //dpm($variables['latest']);
    return $variables;
}

function template_process_islandora_content_stats_data_tpl(&$variables) {
  if(isset($_GET['op'])){
    if($_GET['op']== 'Download History as CSV'){
      islandora_content_stats_csv_download();
    }
  }
}

/**
 * Implements hook_cron().
 * must stay in .module file
 */
function islandora_content_stats_cron() {
    module_load_include('inc', 'islandora_content_stats', 'includes/queries');
    $time = time();
    $is_off_hours = is_off_hours($time);
    $days = 86400 * variable_get('islandora_content_stats_interval');
    $last_run = db_query('select max(timestamp) from {islandora_content_stats}');
    $last_run_time = $last_run->fetchField();
    $elapsed = $time - $last_run_time;
    if ($elapsed > $days && $is_off_hours) {
        islandora_content_stats_run_queries();
    }
}

function is_off_hours($time) {
    $check = strftime('%H', $time);
    $start = variable_get('islandora_content_stats_off_start', 20);
    $end = variable_get('islandora_content_stats_off_end', 23);
    if ($start > $end) {
        $range1 = range($start, 23);
        $range2 = range(0, $end);
        $range = array_merge($range1, $range2);
    } else {
        $range = range($start, $end);
    }
    if (in_array($check, $range)) {
        return TRUE;
    }
}
