<?php

/**
 * Implements hook_menu().
 */
function islandora_content_stats_menu() {
    $items = array();
    $items['admin/islandora/tools/content_stats'] = array(
        'title' => 'Content Statistics',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('islandora_content_stats_admin_form', 1),
        'access arguments' => array('administer site configuration'),
        'file' => 'includes/admin.form.inc',
    );
        $items['data'] = array(
        'title' => 'Content Statistics',
        'page callback' => 'islandora_content_stats_data',
        'page arguments' => array('islandora_content_stats_form'),
        'file' => 'includes/data.form.inc',
        'access callback' => TRUE,
    );
    return $items;
}

function islandora_content_stats_data() {
    return theme('islandora_content_stats_data_tpl');
}

function islandora_content_stats_theme() {
    module_load_include('inc','islandora_content_stats','includes/language');
    module_load_include('inc','islandora_content_stats','includes/utilities');
    module_load_include('inc','islandora_content_stats','includes/queries');
    module_load_include('inc','islandora_content_stats','includes/data.form');
    $params =  drupal_get_query_parameters();
    return array(
        'islandora_content_stats_data_tpl' => array(
            'template' => 'theme/data',
            'render element' => 'form',
            'variables' => array(
                'global_totals' => global_totals(),
                'inst_totals' => inst_totals(),
                'lang' => array(
                  'pageHeader' => lang('pageHeader'),
                  'pageDesc' => lang('pageDesc'),
                  'lastRun' => gmdate("M d Y H:i:s", latest_run()),
                  'globalHeader' => lang('globalHeader'),
                  'globalDesc' => lang('globalDesc'),
                  'instHeader' => lang('instHeader'),
                  'instDesc' => lang('instDesc'),
                  //filters and dl go into form, not tpl
                  //comments kept for mneumonic reasons
                  //'filtersGrouping' => lang('filtersGrouping'),
                  //'filterCmodel_desc' => lang('filterCmodel_desc'),
                  'tableDesc' => lang('tableDesc'),
                  'tableTitle' => lang('tableTitle'),
                  'tableEmpty' => lang('tableEmpty'),
                  //'lang_dl_submit' => lang('downloadSubmitDesc'),
                  //'lang_dl_title' => lang('downloadSubmit'),
                ),
                'params' => $params,
            ),
        ),
    );
}

//code smell and repetition need cleaned.
function template_preprocess_islandora_content_stats_data_tpl(&$variables) {
  module_load_include('inc','islandora_content_stats','includes/utilities');
  module_load_include('inc','islandora_content_stats','includes/data.form');
  $gets = drupal_get_query_parameters();
  if (isset($gets['sortby'])) {
    $order = $gets['order'];
    //existance populates conditionals
    $inst_and_asc = $gets['sortby'] == 'inst' && $gets['order'] == 'asc';
    $cmodel_and_asc = $gets['sortby'] == 'cmodel' && $gets['order'] == 'asc';
    $count_and_asc = $gets['sortby'] == 'count' && $gets['order'] == 'asc';
    //assign ordder based on conditions
    $iorder = ($inst_and_asc) ? 'desc' : 'asc';
    $torder = ($cmodel_and_asc) ? 'desc' : 'asc';
    $corder = ($count_and_asc) ? 'desc' : 'asc';
  }
  else{
    $iorder = 'asc';
    $torder = 'asc';
    $corder = 'asc';
  }
  //defaults
  $inst_get = isset($gets['inst']) ? $gets['inst'] : '';
  $cmodel_get =isset($gets['cmodel']) ? $gets['cmodel'] : '';
  $urls= [];
  $urls['inst'] = array('sortby' => 'inst', 'order' => $iorder, 'inst' => $inst_get,'cmodel'=> $cmodel_get);
  $urls['cmodel'] = array('sortby' => 'cmodel', 'order' => $torder, 'inst' => $inst_get,'cmodel'=> $cmodel_get);
  $urls['count'] = array('sortby' => 'count', 'order' => $corder, 'inst' => $inst_get, 'cmodel'=> $cmodel_get);
  //conditions
  $inst_and_cmodel = isset($gets['inst']) && isset($gets['cmodel']);
  $cmodel_only = isset($gets['cmodel']) && !isset($gets['inst']);
  $inst_only = isset($gets['inst']) && !isset($gets['cmodel']);
  //conditional array population.
  if($inst_and_cmodel){
    foreach ($urls as $url) {
      $url['inst'] = $gets['inst'];
      $url['cmodel'] = $gets['cmodel'];
    }
  }
  if($cmodel_only){
    foreach ($urls as $url){
      $url['cmodel'] =$gets['cmodel'];
    }
  }
  if($inst_only){
    foreach ($urls as $url) {
      $url['inst'] = $gets['url'];
    }
  }
  //rebuild variables and return
  $variables['gets'] = $gets;
  $variables['latest'] = latest_counts_for_table($gets);
  $variables['insturl'] = url('data',array('query' => $urls['inst']));
  $variables['typeurl'] = url('data',array('query' => $urls['cmodel']));
  $variables['counturl'] = url('data',array('query' => $urls['count']));
    return $variables;
}

function template_process_islandora_content_stats_data_tpl() {
  module_load_include('inc','islandora_content_stats','includes/data.form');
  $gets = drupal_get_query_parameters();
  if(isset($gets['op'])){
    if($gets['op']== 'Download History as CSV'){
      islandora_content_stats_csv_download();
    }
  }
}

/**
 * Implements hook_cron().
 * must stay in .module file
 */
function islandora_content_stats_cron() {
    module_load_include('inc', 'islandora_content_stats', 'includes/queries');
    $time = time();
    $is_off_hours = is_off_hours($time);
    $days = 86400 * variable_get('islandora_content_stats_interval');
    $last_run = db_query('select max(timestamp) from {islandora_content_stats}');
    $last_run_time = $last_run->fetchField();
    $elapsed = $time - $last_run_time;
    if ($elapsed > $days && $is_off_hours) {
        islandora_content_stats_run_queries();
    }
}

function is_off_hours($time) {
    $check = strftime('%H', $time);
    $start = variable_get('islandora_content_stats_off_start', 20);
    $end = variable_get('islandora_content_stats_off_end', 23);
    if ($start > $end) {
        $range1 = range($start, 23);
        $range2 = range(0, $end);
        $range = array_merge($range1, $range2);
    } else {
        $range = range($start, $end);
    }
    if (in_array($check, $range)) {
        return TRUE;
    }
}
